### PR TITLE
permanent icon

### PR DESCRIPTION
**Pull request by jakob1379**
added permanent icon for improved interaction with the bare module - could be changed to be a passed argument?

### CODE REVIEW

**Comment by kantord** [comment]
I enjoy that when it's turned off, it's invisible. It cleans up my status bar.

However I see why you'd want this feature, so I'll gladly accept this pull request if you make it optional under some flag, like "--always-visible" or something like that

**Comment by kantord** [comment]
Or it could be `--idle-status="string"` so that any custom emoji or text could be passed

**Comment by kantord** [comment]
feel free to also change README to include your use case: it might be useful for others

**Comment by jakob1379** [comment]
Gotcha - 5min, fam

**Pull request closed without merging**
